### ISSUE TITLE
Add `CLI.Put()`

### ISSUE THREAD

**Issue by clee-omega** [omega-airline-software/ignite-cli#3]
In order to keep devs using the `CLI` class rather than going back and forth between `CLI` and `Console`, we should add `CLI.Put()` which simply calls `CLI.Write()` and has overloads for colors just like `CLI.Out()` does.

**Comment by clee-omega** [comment]
Maybe rename `CLI.Out()` to `CLI.Line()`, and then `CLI.Line()` will call `CLI.Put()` before calling itself without args, keeping DRY.

@ctennery-omega input on naming change

**Comment by ctennery-omega** [comment]
That sounds fine to me.

**Comment by clee-omega** [comment]
It was decided that `CLI.Out()` be the write without newline, and `CLI.Line()` be the write with newline.
