### ISSUE TITLE
Help <Command> Suggestions

### ISSUE THREAD

**Issue by clee-omega** [omega-airline-software/ignite-cli#30]
**This has to be done after #12 (#28)**

Given that the following commands exist:
* `add_user`
* `add_product`
* `delete_user`
* `bad_example`

If a user types `help add`, 'fuzzy search' to print a limited help list that's built from the following matching commands, in order of decreasing similarity (using the same similarity checking as #29) then alphabetically:
* `add_user`
* `add_product`
* `bad_example`

**Comment by ctennery-omega** [comment]
Due to the similarity being the same between `add_user` and `add_product` since they both contain `add`, should it then be printed alphabetically?
* `add_product`
* `add_user`
* `bad_example`
